version: '3.5'

networks:
    torreverseproxy:
        name: torreverseproxy
        external: true

services:
    alice:
        image: nginx
        environment:
            - HIDDENSERVICE_PROFILE=alice
            - HIDDENSERVICE_NAMESPACE=torreverseproxy
        networks:
            - torreverseproxy

    bob:
        image: nginx
        environment:
            - HIDDENSERVICE_PROFILE=bob
            - HIDDENSERVICE_NAMESPACE=torreverseproxy
            - HIDDENSERVICE_PORT=80
        networks:
            - torreverseproxy

    charlie:
        image: nginx
        environment:
            - HIDDENSERVICE_PROFILE=charlie
            - HIDDENSERVICE_NAMESPACE=torreverseproxy
            - HIDDENSERVICE_PORT=80
        networks:
            - torreverseproxy
